version: '2'
services:
  app:
    image: playground
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      .env
    environment:
    - NOT_SO_SECRET=yay
    ports:
      - '8080:8000'
    tty: true
    volumes:
    - .:/app
